version: '3.9'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=lighthouse
            - POSTGRES_USER=lighthouse
            - POSTGRES_PASSWORD=lighthouse
    main:
        build: .
        volumes:
            - .:/usr/app
        ports:
            - "8000:8000"